# Generated by Django 4.2.19 on 2025-02-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='1234567', max_length=10),
        ),
    ]
