# Generated by Django 4.2.19 on 2025-02-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0002_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='1234', max_length=4),
        ),
    ]
