# Generated by Django 4.2.19 on 2025-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerAuth', '0003_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='1234', max_length=30),
        ),
    ]
